# SPDX-License-Identifier: Unlicense
# SPDX-FileCopyrightText: Czech Technical University in Prague

# An example launch file for running a filter on Image messages. This example showcases that the filter chain uses
# image_transport to subscribe and publish.
# Author: Martin Pecka

/**:
  ros__parameters:
    image_transport: compressed
    output_queue_size: 101
    publication_type: unique_ptr
    image_filter_chain$(var lifecycle_suffix):
      filter1:
        # This filter will subtract 25 ms from each image timestamp, e.g. to account for transport delay.
        name: delay
        type: sensor_filters/ChangeHeader_Image
        params:
          stamp_relative: -0.025
