# SPDX-License-Identifier: Unlicense
# SPDX-FileCopyrightText: Czech Technical University in Prague

# An example launch file for running a filter on PointCloud2 messages. This example showcases that the filter chain uses
# point_cloud_transport to subscribe and publish.
# Author: Martin Pecka

/**:
  ros__parameters:
    point_cloud_transport: draco  # this transport is used for subscribing the filter input
    output_queue_size: 10
    publication_type: shared_ptr
    pointcloud2_filter_chain$(var lifecycle_suffix):
      filter1:
        # This filter will subtract 25 ms from each cloud timestamp, e.g. to account for transport delay.
        name: delay
        type: sensor_filters/ChangeHeader_PointCloud2
        params:
          stamp_relative: -0.025
