set(MESSAGE_HEADER "sensor_msgs/msg/${HEADER_NAME}.hpp")

if (BASE_FILTER)
    set(TEMPLATE_ARGS "sensor_msgs::msg::${MESSAGE_TYPE}, sensor_filters::${BASE_FILTER}")
    set(BASE_INCLUDE "#include <sensor_filters/${BASE_FILTER}.hpp>")
else ()
    set(TEMPLATE_ARGS "sensor_msgs::msg::${MESSAGE_TYPE}")
    set(BASE_INCLUDE "")
endif ()

if (LIFECYCLE)
    configure_file(${PROJECT_SOURCE_DIR}/cmake/LifecycleFilterChainNode.cpp.in ${OUTPUT_FILE} @ONLY)
else ()
    configure_file(${PROJECT_SOURCE_DIR}/cmake/FilterChainNode.cpp.in ${OUTPUT_FILE} @ONLY)
endif ()
