# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

name: License lint

# This determines when this workflow is run
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  license_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5